version: "3.7"
services:
  app:
    build: app
    ports:
      - 3000:3000
  web:
    build: nginx
    ports:
      - 80:80
  db:
    build: postgres
    ports:
      - 5432:5432
    volumes:
      - .pgdata:/var/lib/postgresql/data
